agent {
    data_dir = "/home/ubuntu/zero-trust-spiffe-lab/spire/data/agent"
    log_level = "DEBUG"
    server_address = "127.0.0.1"
    server_port = "8081"
    socket_path = "/tmp/spire-agent/public/api.sock"
    trust_domain = "example.org"
    insecure_bootstrap = true
    join_token = "15b9824c-1c08-4bd0-9962-7329b9638a98"
}

plugins {
    NodeAttestor "join_token" {
        plugin_data {}
    }

    KeyManager "disk" {
        plugin_data {
            directory = "/home/ubuntu/zero-trust-spiffe-lab/spire/data/agent"
        }
    }

    WorkloadAttestor "unix" {
        plugin_data {}
    }
}
